# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postaus',
            new_name='Post',
        ),
    ]
